### ISSUE TITLE
ruamel to_yaml TypeError with SafeDumper

### ISSUE THREAD

**Issue by ksindi** [cdgriffith/Box#118]
Using latest version of box. I just came across an issue with ruamel to_yaml getting an unexpected keyword argument when using SafeDumper:

```
import box
import yaml

b = box.Box({"a": 1})
b.to_yaml()  # 'a: 1\n'

b.to_yaml(Dumper=yaml.dumper.SafeDumper)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/box/box.py", line 662, in to_yaml
    encoding=encoding, errors=errors, **yaml_kwargs)
  File "/usr/local/lib/python3.7/site-packages/box/converters.py", line 70, in _to_yaml
    return yaml.dump(obj, default_flow_style=default_flow_style, **yaml_kwargs)
  File "/usr/local/lib/python3.7/site-packages/ruamel/yaml/main.py", line 1248, in dump
    block_seq_indent=block_seq_indent,
  File "/usr/local/lib/python3.7/site-packages/ruamel/yaml/main.py", line 1184, in dump_all
    prefix_colon=prefix_colon,
TypeError: __init__() got an unexpected keyword argument 'block_seq_indent'
```

Stack:
```
python_box-4.0.1
ruamel.yaml-0.16.5
```

**Comment by ksindi** [comment]
Never mind. Should be importing ruamel.
