### ISSUE TITLE
BoxKeyError when constructing a Box with box_dots = True in v7.0.0

### ISSUE THREAD

**Issue by roosephu** [cdgriffith/Box#250]
To reproduce: 
```
>>> import box
>>> box.__version__
'7.0.0'
>>> box.Box({'a.b': 1})
Box({'a.b': 1})
>>> box.Box({'a.b': 1}, box_dots=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "box/box.py", line 286, in box.box.Box.__init__
  File "box/box.py", line 653, in box.box.Box.__setitem__
box.exceptions.BoxKeyError: "'<class 'box.box.Box'>' object has no attribute a"
```

It seems to work in v6.0.2: 

```
>>> import box
>>> box.__version__
'6.0.2'
>>> box.Box({'a.b': 1})
Box({'a.b': 1})
>>> box.Box({'a.b': 1}, box_dots=True)
Box({'a.b': 1})
```

Python 3.10.9.

**Comment by roosephu** [comment]
This might be related to #170.
```
>>> import box
>>> box.__version__
'7.0.0'
>>> box.Box({'a.b': 1}, default_box=True)
Box({'a.b': 1})
>>> box.Box({'a.b': 1}, default_box=True, box_dots=True)
Box({'a': {'b': 1}})
```

That is, we have to set `default_box=True` to avoid BoxKeyError.

**Comment by roosephu** [comment]
Found this is in the list of [breaking changes](https://github.com/cdgriffith/Box/wiki/Major-Version-Breaking-Changes#box-dots-now-treats-any-key-with--in-it-as-if-it-should-be-split) which unfortunately I didn't read through. The examples in the [wiki](https://github.com/cdgriffith/Box/wiki/Types-of-Boxes#box-dots) should be updated, though.
