### ISSUE TITLE
Support for non-string keys

### ISSUE THREAD

**Issue by polishmatt** [cdgriffith/Box#48]
I specifically ran into this issue when calling to_dict on a Box instance with an integer key. A TypeError is raised on this line:
https://github.com/cdgriffith/Box/blob/37ad92655da7dc31d3cd55ffab304ea2a0d68a72/box.py#L524
`TypeError: attribute name must be string, not 'int'`
I saw the issue when using Python 3.5.2.

The following works for an integer key:
`self[key] = value`
so the change may be as simple as adding TypeError to line 525:
https://github.com/cdgriffith/Box/blob/37ad92655da7dc31d3cd55ffab304ea2a0d68a72/box.py#L525

This was not an issue in 2.0 and most likely later versions, although it may not have been intentionally supported:
https://github.com/cdgriffith/Box/blob/8340399c659b274d9bdec452684f4ace0d844164/box.py#L71
As a result I would argue this is a bug not a feature request.

**Comment by cdgriffith** [comment]
I will have to think about this more / get more feedback, but right now it sounds like it's acting like Python expects. (That you can have integers, really anything hashable, as keys of the dict. But attributes have to be strictly strings) 

```python
>>> class A:
...     pass
...
>>> a = A()
>>> b = dict()
>>> b[1] = 1
>>> setattr(a, 1, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: attribute name must be string, not 'int'
```

Python will raise unavoidable syntax errors if someones tries to access or set an integer via dot notation, so that can't be circumvented (i.e. `a.1 = 1` would raise SyntaxError). So someone would have to be using `getattr`, `setattr` or manually calling the magic functions to see this error, which is already past the point of this module trying to be handy by allowing access dot attribute access to non-string keys.

**Comment by polishmatt** [comment]
Sorry the actual issue is in update, not to_dict. I have to cut off the top of the stack trace but it starts with a call to update on a Box instance:

```
  File "/usr/lib/python3.5/site-packages/box.py", line 598, in update
    self[k].update(v)
  File "/usr/lib/python3.5/site-packages/box.py", line 598, in update
    self[k].update(v)
  File "/usr/lib/python3.5/site-packages/box.py", line 602, in update
    self.__setattr__(k, v)
  File "/usr/lib/python3.5/site-packages/box.py", line 524, in __setattr__
    object.__getattribute__(self, key)
TypeError: attribute name must be string, not 'int'
```

**Comment by cdgriffith** [comment]
Oh ho, got ya now. 

Issue is right where you listed at https://github.com/cdgriffith/Box/blob/master/box.py#L602 where I am calling `__setattr__` on everything in `update`. I need to either check that it's a string or raise a type error.

**Comment by polishmatt** [comment]
Well a TypeError is already raised eventually in __setattr__. I'm not sure that it's an improvement to move it to update since the exception message already seems fairly clear.

It's up to you if you think it doesn't make sense for this package to support non-string keys but that seems to conflict with the stated mission of 'an easy drop in transparently replacements for dictionaries'.

**Comment by cdgriffith** [comment]
errp, mispoke, meant to say catch the raised type error there (aka so during `update` if a key is non string, trying to make it an attribute is ignored and no error occurs) . It needs to support non string keys, just not non-string attributes. Good catch!
